export const SUBMIT_SCORE = 'SUBMIT_SCORE';
export const SUBMIT_RANDOM_SCORE = 'SUBMIT_RANDOM_SCORE';
export const CHANGE_SCORE = 'CHANGE_SCORE';
export const CHANGE_PLAYERS = 'CHANGE_PLAYERS';
export const FINISH_GAME = 'FINISH_GAME';
export const START_GAME = 'START_GAME';
